<a href="https://colab.research.google.com/github/veekthorcodes/learning-tensoflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concepts of tesors with TensorFlow

More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function ( a way to speed up your regular python functions)
* Exercises to try for yourself

## Introduction to Tensors

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.6.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimensions of a tensor (ndim stands for the number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of our vector
vector.ndim

1

In [ ]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [5.,6.],
                              [12., 6]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 5.,  6.],
       [12.,  6.]], dtype=float16)>

In [ ]:
# What is the number of another_matrix
another_matrix.ndim

2

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3,],
                       [4, 5, 6]],
                      [[7, 8, 9,],
                      [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we've created so far:
* Scalar: a single number
* Vector: a number with direction (e.g wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers ( when n can be any number representing the dimension)

## Creating tensors with `tf.Variable`

In [ ]:
# Create the same tensor with tf.Variable() as above

changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try to change an element in out changeable tensor
# changeable_tensor[0] = 7

In [ ]:
# How about we try .assign
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Let's try to change our unchangeable tensor
# unchangeable_tensor[0].assign(7)
# unchangeable_tensor

### Creating random tensors

Random tensors are tensors of arbitrary size of random numbers

In [ ]:
# Create two random but the same tensors
random_1 = tf.random.Generator.from_seed(6)
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(6)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.97061104, -1.0242516 ],
        [-0.6544423 , -0.29738766],
        [-1.3240396 ,  0.28785667]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.97061104, -1.0242516 ],
        [-0.6544423 , -0.29738766],
        [-1.3240396 ,  0.28785667]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order does not affect learning)
not_shuffled = tf.constant([[10, 7],
                            [2, 5], 
                            [3,6]])
# Shuffle our not_shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  6],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  6]], dtype=int32)>

In [ ]:
a = tf.constant([1, 2, 3])
a = tf.random.shuffle(a)
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 1], dtype=int32)>

In [ ]:
tf.random.set_seed(6)
b = tf.constant([1, 2, 3])
b = tf.random.shuffle(b)
b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 2, 1], dtype=int32)>

In [ ]:
b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 2, 1], dtype=int32)>

In [ ]:
# tf.random.set_seed(4)
c = tf.constant([4, 5, 6])
c = tf.random.shuffle(c, seed=(6))
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([6, 4, 5], dtype=int32)>

In [ ]:
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([6, 4, 5], dtype=int32)>

## Other ways to make tensors

In [ ]:
# create a tensor of all ones
ones = tf.ones([3,6])
ones

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create a tensor of all zeros
ze = tf.zeros(shape=(3,4))
ze

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

# Turn Numpy arrays to Tensors

In [ ]:
import numpy as np

numpy_A = np.arange(1,25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2, 2, 2, 3))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 2, 2, 3), dtype=int32, numpy=
 array([[[[ 1,  2,  3],
          [ 4,  5,  6]],
 
         [[ 7,  8,  9],
          [10, 11, 12]]],
 
 
        [[[13, 14, 15],
          [16, 17, 18]],
 
         [[19, 20, 21],
          [22, 23, 24]]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
A.ndim

4

In [ ]:
tf.size(A)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

### Getting information from tensors

# When dealing with tensors, be aware of the following attributes
* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
# Create a rank 4 tensor (4 dimensioins)
r4_tensor = tf.zeros(shape=(2,2,3,4))
r4_tensor

<tf.Tensor: shape=(2, 2, 3, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
r4_tensor[0]

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
r4_tensor.shape, r4_tensor.ndim, tf.size(r4_tensor)

(TensorShape([2, 2, 3, 4]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=48>)

In [ ]:
# Get various attributes of our tensor
print("Datatype of every element:", r4_tensor.dtype)
print("Number of dimensions (rank):", r4_tensor.ndim)
print("Shape of tensor:", r4_tensor.shape)
print("Elements along axis 0:", r4_tensor.shape[0])
print("Elements along the last axis:", r4_tensor.shape[-1])
print("Total number of elements in the tensor:", tf.size(r4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 2, 3, 4)
Elements along axis 0: 2
Elements along the last axis: 4
Total number of elements in the tensor: 48


### Indexing tensors
Tensors can be indexed just like Python lists

In [ ]:
# Get the first 2 elements of each dimension
r4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension except the last one
r4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=array([[[[0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor
rank_2_tensor = tf.constant([[3, 6],
                            [10, 7]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
# Get the last item of each row of rank_2_tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 7], dtype=int32)>

In [ ]:
# Add an extra dimension to rank_2_tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 3],
        [ 6]],

       [[10],
        [ 7]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 3],
        [ 6]],

       [[10],
        [ 7]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 3],
        [ 6]],

       [[10],
        [ 7]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_3_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2, 1), dtype=int32, numpy=
array([[[[ 3],
         [ 6]],

        [[10],
         [ 7]]]], dtype=int32)>

### Tensor Operations in TensorFlow

In [ ]:
a = tf.constant([[10, 7], [3, 6]])
b = tf.constant([[5, 5], [2, 4]])
print(a, b)

# Add
print("ADD")
print(tf.add(a, b))

#subtract
print(tf.subtract(a, b))

#multiply
print(tf.multiply(a, b))

#divide
print(tf.divide(a, b))

tf.Tensor(
[[10  7]
 [ 3  6]], shape=(2, 2), dtype=int32) tf.Tensor(
[[5 5]
 [2 4]], shape=(2, 2), dtype=int32)
ADD
tf.Tensor(
[[15 12]
 [ 5 10]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[5 2]
 [1 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[50 35]
 [ 6 24]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2.  1.4]
 [1.5 1.5]], shape=(2, 2), dtype=float64)


In [ ]:
tf.matmul(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[64, 78],
       [27, 39]], dtype=int32)>

In [ ]:
import tensorflow as tf

a = tf.constant([[1, 2, 5,],
                 [7, 2, 1,],
                 [3, 3, 3,]
                 ])

b = tf.constant([[3, 5,],
                 [6, 7,],
                 [1, 8,]])

c =tf.matmul(a, b)
c

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# Matrix multiplication with Python operator "@"
a @ b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
a.shape

TensorShape([3, 3])

In [ ]:
b.shape
b
tf.reshape(b, (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 5, 6],
       [7, 1, 8]], dtype=int32)>

In [ ]:
b @ tf.reshape(b, (2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[44, 20, 58],
       [67, 37, 92],
       [59, 13, 70]], dtype=int32)>

In [ ]:
tf.reshape(b, (2, 3)) @ b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 45,  98],
       [ 35, 106]], dtype=int32)>

**The dot product**

Matric multiplication is also referred to as the dot product.

You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`

In [ ]:
X = tf.constant([[1, 2],
                 [3, 4], 
                 [5, 6]])
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Check the values of Y, reshape Y and transposed Y
print("Normal Y:")
print(Y, "\n")

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [ ]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

### Changing the datatype of a tensor

In [ ]:
# create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [ ]:
C = tf.constant([7, 5])
C.dtype

tf.int32

In [ ]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([7., 5.], dtype=float32)>,
 tf.float32)

### Aggregating tensors

Aggregating tensors: condensing them from multiple values down to smaller amount of values.

In [ ]:
# Getting the absolute values
F = tf.constant([-7, -6])
F

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-7, -6], dtype=int32)>

In [ ]:
tf.abs(F)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 6], dtype=int32)>

Different forms of aggregation:
* Get the minimun
* Get the maximun
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
V = tf.constant([[1, 2, 3],
                 [6, 7, 8]])

print("minimum:", tf.reduce_min(V).numpy())
print("maximum:", tf.reduce_max(V).numpy())
print("mean:", tf.reduce_mean(V).numpy())

minimum: 1
maximum: 8
mean: 4


In [ ]:
# Create a random tensor with values between 0 and 100 size of 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([34, 53, 51,  7, 77, 12, 66, 99, 31, 73, 88, 19, 46, 67, 70, 89, 10,
       37, 88, 48, 84, 57, 62, 55,  9, 84, 38, 88, 92, 21, 22, 80, 14, 49,
       26, 35, 29, 51, 61, 86, 74, 16, 11, 30,  5,  4, 88, 98, 68, 61])>

In [ ]:
E.shape, tf.size(E), E.ndim

(TensorShape([50]), <tf.Tensor: shape=(), dtype=int32, numpy=50>, 1)

In [ ]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [ ]:
np.min(E)

4

In [ ]:
# Find max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=51>

In [ ]:
# Find the 

tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2563>

In [ ]:
E = tf.cast(E, dtype=tf.float32)
tf.math.reduce_variance(E).numpy(), tf.math.reduce_std(E).numpy() # Finding variance with tf.math

(832.71234, 28.856756)

In [ ]:
# finding the variance and std with tfp (tensorflow_probability)
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=float32, numpy=832.71234>

### Finding the positional maximum and minimum  

In [ ]:
# Find the positional max (argmax)
tf.argmax(E)

<tf.Tensor: shape=(), dtype=int64, numpy=7>

In [ ]:
E[7]

<tf.Tensor: shape=(), dtype=float32, numpy=99.0>

In [ ]:
tf.argmin(E)

<tf.Tensor: shape=(), dtype=int64, numpy=45>

In [ ]:
E[45]

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [ ]:
 # Create a new tensor for finding positional minimum and maximum
 tf.random.set_seed(42)
 F = tf.random.uniform(shape=[50])
 F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Index out largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor to get started
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeeze = tf.squeeze(G)
G_squeeze, G_squeeze.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
        0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
        0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
        0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
        0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
        0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
       dtype=float32)>, TensorShape([50]))

### One hot encoding tensors

In [ ]:
# Create a list of indices
some_list = [0, 1, 2, 3] # could be 4 different colors

# One hot encoding
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding
# tf.one_hot(some_list, depth=4, on_value="yo I love deep learning", off_value="I love playing the drums")

### Squaring, log, square root

In [ ]:
# Create a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Find the square root
tf.sqrt(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [ ]:
# Find the log
tf.math.log(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

## Tensors and Numpy\

Tensoflow interacts beautifully with Numpy arrays

In [ ]:
# Create a tensor directly from a Numpy array
J = tf.constant(np.array([3., 4., 5.,]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 4., 5.])>

In [ ]:
# convert tensor back to Numpy array
np.array(J), type(np.array(J))

(array([3., 4., 5.]), numpy.ndarray)

In [ ]:
# Convert tensor J to a Numpy array
J.numpy(), type(J.numpy())

(array([3., 4., 5.]), numpy.ndarray)

In [ ]:
# The default type of each are quite different
numpy_J = tf.constant(np.array([2., 3., 4.,]))
tensor_J = tf.constant([3., 7., 10.])

# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

## Finding access to GPU

In [ ]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [ ]:
tf.config.list_physical_devices("GPU")

[]

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Fri Sep 10 21:39:39 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.63.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P8    27W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

sample_data/
